routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['reset'=>false]);

//default landing page
Route::get('/', 'HomeController@index');

//authenticated landing page
Route::get('/home', 'StudyController@index')->name('studies.index ');

//login and registration
Route::get('/login', 'Auth\LoginController@show')->name('login');
Route::get('/register', 'Auth\RegisterController@show')->name('register');

//user settings
Route::get('/setting', 'SettingController@index')->name('setting');

/*
  Admin Management
*/

Route::get('/system', 'UserController@index')->name('system');

//user management
Route::get('/system/users/create', 'UserController@create')->name('systems.users.create');
Route::get('/system/users/{user}/profile', 'UserController@profile')->name('systems.users.profile');
Route::get('/system/users/{user}/edit', 'UserController@edit')->name('systems.users.edit');
Route::get('/system/users', 'UserController@index')->name('systems.users.index');

Route::post('/system/users/store', 'UserController@store')->name('systems.users.store');
Route::patch('/system/users/{user}/update', 'UserController@update')->name('systems.users.update');
Route::delete('/system/users/{user}/delete', 'UserController@destroy')->name('systems.users.delete');

/*
  Studies
*/

Route::get('/studies', 'StudyController@index')->name('studies.index');
Route::post('/studies/store', 'StudyController@store')->name('studies.store');
Route::get('/studies/create', 'StudyController@create')->name('studies.create');
Route::post('/studies/basis', 'StudyController@basis')->name('studies.basis');
Route::post('/studies/{study}/basisOptions', 'StudyController@basisOptions')->name('studies.basisOptions');
Route::post('/studies/{study}/basisFIDA', 'StudyController@basisFIDA')->name('studies.basisFIDA');
Route::post('/studies/{study}/basisUpload', 'StudyController@basisUpload')->name('studies.basisUpload');
Route::get('/studies/{study}', 'Session\SessionController@index')->name('studies.show');

//search
Route::post('/studies/search', 'StudyController@search')->name('studies.search');
Route::get('/studies/search', 'StudyController@searchIndex')->name('studies.search.index');

//collab
Route::get('/studies/{study}/sessions/collab', 'CollabController@index')->name('studies.collab');
Route::post('/studies/{study}/sessions/collab', 'CollabController@search')->name('studies.collab.search.user');
Route::post('/studies/{study}/sessions/collab/add', 'CollabController@add')->name('studies.collab.add');
Route::post('/studies/{study}/sessions/collab/remove', 'CollabController@remove')->name('studies.collab.remove');

/*
  Session
*/

Route::resource('sessions', 'Session\SessionController', [
  'except' => ['index']
]);

Route::prefix('studies/{study}/sessions')->name('sessions.')->group(function () {
    Route::get('/', 'Session\SessionController@index')->name('index');
});

Route::prefix('sessions')->name('sessions.')->group(function () {
    Route::get('{session}/detail', 'Session\SessionController@index')->name('detail');
    Route::get('{session}/preprocess', 'Session\PreprocessController@index')->name('preprocess');
    Route::get('{session}/voxel', 'Session\DicomController@index')->name('voxel');
    Route::get('{session}/analysis', 'Session\AnalysisController@index')->name('analysis');
    Route::get('{session}/analysis/{analysis}/show', 'Session\AnalysisController@show')->name('analysis.show');
    Route::get('{session}/analysis/create', 'Session\AnalysisController@create')->name('analysis.create');
    Route::post('{session}/analysis/store', 'Session\AnalysisController@store')->name('analysis.store');
    Route::get('{session}/brainbrowser', 'Session\BrainBrowserController@index')->name('brainbrowser');
    Route::get('{session}/uploads', 'Session\UploadController@index')->name('upload');
});


//File
Route::get('file/{id}', 'FileController@display')->where('id', '.*')->name('file.display');
Route::get('download/{id}', 'FileController@download')->where('id', '.*')->name('file.download');

//Analysis results
Route::get('analysis/result/{id}', 'AnalysisResultsController@display')->where('id', '.*')->name('analysis.display');
Route::get('analysis/download/{id}', 'AnalysisResultsController@download')->where('id', '.*')->name('analysis.download');

//INVITATION
/**
 * Override the default auth register route to add middleware.
 */
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register')->middleware('hasInvitation');
Route::get('register/request', 'Auth\RegisterController@requestInvitation')->name('requestInvitation');

/**
 * Invitations group with auth middleware.
 * Eventhough we only have one route currently, the route group is for future updates.
 */
Route::group([
    'prefix' => 'invitations'
], function() {
    Route::get('', 'InvitationsController@index')->name('showInvitations');
});

/**
 * Route for storing the invitation. Only for guest users.
 */
Route::post('invitations', 'InvitationsController@store')->middleware('guest')->name('storeInvitation');
Route::get('invitations/send', 'InvitationsController@send')->name('sendInvitation');
Route::post('/studies/{study}/sessions/invitations/assign', 'InvitationsController@assign')->name('assignInvitation');

app/Study.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Searchable\Searchable;
use Spatie\Searchable\SearchResult;

class Study extends Model implements Searchable
{
  
  protected $fillable = ['name'];
  
  public function user()
  {
    return $this->belongsTo('App\User');
  }
  
  public function sessions() {
    return $this->hasMany('App\Session');
  }

  public function basis() {
    return $this->hasMany('App\Basis');
  }

  public function files()
  {
     return $this->hasMany('App\File');
     // return $this->morphMany('App/File','filable');
  }
  
  public function getSearchResult(): SearchResult
  {
    $url = route('studies.show', $this->id);

      return new SearchResult(
        $this,
        $this->name,
        $url
      );
  }
}

app/Http/Controllers/StudyController.php
<?php

namespace App\Http\Controllers;

use Storage;
use App\Study;
use App\Basis;
use App\File;
use App\Jobs\ProcessBasisSimulation;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Validator;

use Spatie\Permission\Models\Permission;

//searching package for searching
use Spatie\Searchable\Search;



class StudyController extends Controller
{
  
  public function __construct()
  {
    $this->middleware('auth');
  }
  
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
    
      $this->authorize('list', Study::class);
      
      // get all the studies
      $studies = Study::all();
      $studies = $studies->reject( function ($study, $key) {
        return auth()->user()->cannot("access$study->id");
      });
      
      // load the view and pass the studies
      return view('studies.index')->with('studies',$studies);
  }

  /**
   * Create a new study
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
      $this->authorize('create', Study::class);
      return view('studies.create');
  }


    /**
     * Create a new study
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function basis(Request $request)
    {
      
        $this->authorize('create', Study::class);
      
        $validatedData = $request->validate([
          'studyName' => 'bail|required|unique:studies,name|max:255',
          'studyType' => 'bail|required|max:255',
         ]);
         
        $studyName = $request->input('studyName');
        $studyType = $request->input('studyType');

        $study = new Study();
        $study->name = $studyName;
        $study->type = $studyType;
        $study->user_id = Auth::id();
        $study->save();
        
        //create permission to access study being created
        $permission = Permission::create(['name' => 'access' . $study->id]);
        //assign self to study you created
        auth()->user()->givePermissionTo($permission);
        
        // Store Study with default basis options
        if ($request->input('button') == 'create') {
            return redirect()->route('studies.index');
        }
        return view('studies.basis')->with(['study' => $study]);
    }

    /**
     * Store a new study
     *
     * @param  \Illuminate\Http\Request
     * @return \Illuminate\Http\Response
     */
    public function basisOptions(Request $request, Study $study)
    {

        $this->authorize('create', Study::class);
        
        $validator = Validator::make($request->all(), [
          'studyName' => 'bail|required|max:255',
          'studyType' => 'bail|required|max:255',
          'method' => 'nullable',
          'press' => 'nullable',
          'megapress' => 'nullable',
        ]);

        if ($validator->fails()) {
            return redirect('studies/create')
                        ->withErrors($validator)
                        ->withInput();
        }
         
        $studyName = $request->input('studyName');
        $studyType = $request->input('studyType');
        $press = ($request->input('press') == "on");
        $megapress = ($request->input('megapress') == "on");
        $method = $request->input('method');

        $study->name = $studyName;
        $study->type = $studyType;
        $study->user_id = Auth::id();
        $study->basisMethod = $method;

        //Log::debug("creating $study->name and its not null!");
        if ($press) {
            $pressBasis = new Basis();
            $pressBasis->seq = 'press';
            $pressBasis->study()->associate($study);
            $pressBasis->save();
        }

        if ($megapress) {
            $megapressBasis = new Basis();
            $megapressBasis->seq = 'megapress';
            $megapressBasis->study()->associate($study);
            $megapressBasis->save();
        }

        $study->save();

        Log::debug("Looping through basis");

        switch ($method) {
            case 'FID-A':
                return view('studies.basisFIDA')->with(['study' => $study]);
                break;
            case 'TARQUIN':
                return redirect()->route('studies.index');
                break;
            case 'Upload':
                return view('studies.basisUpload')->with(['study' => $study]);
                break;
        }
        return view('studies.create');
    }

    /**
     * Store a new study
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function basisFIDA(Request $request, Study $study)
    {
        $this->authorize('create', Study::class);

        $count = 0;
        foreach ($study->basis as $basis) {
            $samplingFrequency = $request->input('samplingFrequency');
            $echoTime = $request->input('echoTime');
            $basis->samplingFreq = $samplingFrequency[$count];
            $basis->echoTime = $echoTime[$count];

            log::debug('Generating new custom basis file');
            log::debug("echo time: $echoTime[$count]");
            log::debug("sampling frequency: $samplingFrequency[$count]");
            $basisFileName = str_random(40);
            Log::debug("file name: $basisFileName");
            $pathBasis = $basis->seq . 'Basis' . DIRECTORY_SEPARATOR . $basisFileName;
            Storage::put($pathBasis, "");
            Log::debug("file location: $pathBasis");
            $study->files()->save(new \App\File(['path' => $pathBasis, 'type' => 'basis']));
            $basis->path = $pathBasis;

            $basis->save();
            $study->save();
  
            ProcessBasisSimulation::dispatch($pathBasis, $study, $echoTime[$count], $samplingFrequency[$count]);

            $count += 1;
            Log::debug("Sampling Frequency: $basis->samplingFrequency" );
           // $basis->transmitterFrequency = $request->input($seq . 'transmitterFrequency');
        }

        return redirect()->route('studies.index');
    }

    /**
     * Create a new study with custom basis file
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     **/
    public function basisUpload(Request $request, Study $study)
    {
        $this->authorize('create', Study::class);
        return view('studies.basisUpload')->with(['study' => $study]);
    }

    /**
     * Store a new study
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Study $study)
    {
      
        $this->authorize('create', Study::class);

        if (!$request->has('basis')) {
            return view('studies.basisUpload')->with(['study' => $study]);
        }

        $basisSet = $request->file('basis');
        $count = 0;
        foreach ($study->basis as $basis) {
            
            $seq = $basis->seq;
            log::debug('Uploading press basis file');
            $fileName = str_random(40);
            $basisFileName = $fileName . '.basis';
            $pathBasis = Storage::putFileAs( $seq . 'Basis', $basisSet[$count], $basisFileName);
            $filePath = storage_path() . '/' . 'app/' . $pathBasis;
            $study->basis->path = $filePath;
            Log::debug("file location: $filePath");
            $study->files()->save(new \App\File(['path' => $pathBasis, 'type' => 'basis']));
            $study->save();
            $count++;
            
        }

        //create permission to access this session
        $permission = Permission::create(['name' => 'access' . $study->id]);
        //assign self to study you created
        auth()->user()->givePermissionTo($permission);

        return redirect()->route('studies.index');
    }

    //building search
    public function search(Request $request)
    {
        $this->authorize('list', Study::class);
        
        $validatedData = $request->validate([
           'searchStudyByName' => 'required',
         ]);
        
        // user search
        $studySearchResults = Study::where('name', 'like', "%{$request->searchStudyByName}%")
                                ->take(20)
                                ->get();
                  
        $studySearchResults = $studySearchResults->reject(function ($study, $key) {
            return !Auth::user()->can("access$study->id");
        });

        return view('studies.search', compact('studySearchResults'));
    }
    
    public function searchIndex(Request $request)
    {
        return view('studies.search');
    }
}

resources/views/studies/basis.blade.php
@extends('layouts.app')

@section('content')
<div class="card">
    <div class="card-header">
        <b>Basis Set Options</b>
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route('studies.basisOptions', [$study]) }}" enctype="multipart/form-data">
            @csrf

            <div class="form-group row">
                <div class="col">
                    <label for="studyName">Name of Study</label>
                    <input type="text" class="form-control" id="studyName" name="studyName" placeholder="E.g. Alzheimer Study" value={{$study->name}} >
                </div>
            </div>
            <div class="form-group row">
                <div class="col">
                    <label for="studyType">Study Type</label>
                    <input type="text" class="form-control" id="studyType" name="studyType" placeholder="E.g. Alzheimer" value={{$study->type}} >
                </div>
            </div>

            <div class="form-group row">
                <div class="col">
                    <label for="sel1">Basis Simulation Method:</label>
                    <select class="form-control" id="method" name="method">
                        <option>TARQUIN</option>
                        <!-- <option>FID-A</option> -->
                        <option>Upload</option>
                    </select>
                </div>
            </div>

            <div class="form-check row">
            <label for="studyType">Add sequences to your study</label>
                <div class="col">
                    <input type="checkbox" class="form-check-input" id="press" name="press">
                    <label class="form-check-label" for="press">PRESS</label>
                </div>
                <div class="col">
                    <input type="checkbox" class="form-check-input" id="megapress" name="megapress">
                    <label class="form-check-label" for="megapress">MEGAPRESS</label>
                </div>
            </div>
            

            <button type="submit" name="button" value="create" class="btn btn-primary">Create Study</button>

        </form>

    </div>
</div>
@endsection

resources/views/studies/basisFIDA.blade.php
@extends('layouts.app')

@section('content')
<div class="card">
    <div class="card-header">
        <b>Basis Set Options</b>
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route('studies.basisFIDA', [$study]) }}" enctype="multipart/form-data">
            @csrf

            @foreach($study->basis as $basis)
            <label>{{$basis->seq}} Basis Simulation</label>
            <div class="form-group row">
                <div class="col">
                    <label for="samplingFrequency">Sampling Frequency (Hz)</label>
                    <input type="text" class="form-control" id="samplingFrequency[]" name="samplingFrequency[]" value={{ $basis->samplingFreq }}>
                </div>
                <div class="col">
                    <label for="transmitterFrequency"> Transmitter Frequency (Hz)</label>
                    <input type="text" class="form-control" id="transmitterFrequency[]" name="transmitterFrequency[]" value={{ $basis->transmitterFreq }}>
                </div>

            </div>
            
            <div class="form-group row">
                <div class="col">
                    <label for="magneticFieldStrength">Magnetic Field Strength (T)</label>
                    <input type="text" class="form-control" id="magneticFieldStrength[]" name="magneticFieldStrength[]" value={{ $basis->bfield }}>
                </div>
                <div class="col">
                    <label for="echoTime">Echo Time (ms)</label>
                    <input type="text" class="form-control" id="echoTime[]" name="echoTime[]" value={{ $basis->echoTime }}>
                </div>

            </div>
            @endforeach

    
    <button type="submit" name="button" value="create" class="btn btn-primary">Create Study</button>

    </form>
</div>
</div>
@endsection

resources/views/studies/basisUpload.blade.php
@extends('layouts.app')

@section('content')
<div class="card">
    <div class="card-header">
        <b>Basis Set Options</b>
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route('studies.store') }}" enctype="multipart/form-data">
            @csrf

            @foreach($study->basis as $basis)
            <label>{{$basis->seq}} Basis File Upload</label>
            <div class="form-group row">
                <div class="col">
                    
                    <input type="file" id="basis" name="basis" class="form-control-file">
                </div>
            </div>
            @endforeach
  

    <button type="submit" name="button" value="create" class="btn btn-primary">Create Study</button>

    </form>

</div>
</div>
@endsection

resources/views/studies/collab.blade.php
@extends('layouts.app')

@section('content')
<div class="container mb-2">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <b>Find the person to share</b>
                </div>

                <div class="card-body">
                    <div class="container">
                      <form class="form-horizontal" method="POST" action="{{ route('studies.collab.search.user', $study) }}">
                          {{ csrf_field() }}

                          <div class="form-group{{ $errors->has('people') ? ' has-error' : '' }}">
                              <label for="search" class="col-md-4 control-label">People</label>

                              <div class="col-md-12">
                                  <input pattern=".{2,100}" required title="2 to 100 characters" id="people" type="people" class="form-control" name="people" value="{{ old('people') }}" required autofocus>

                                  @if ($errors->has('people'))
                                      <span class="help-block">
                                          <strong>{{ $errors->first('people') }}</strong>
                                      </span>
                                  @endif
                              </div>
                          </div>

                          <div class="form-group">
                              <div class="col-md-8">
                                  <button 
                                    type="submit" 
                                    class="btn btn-primary btn-sm"
                                    dusk="collab-people-search-button"
                                  >
                                      Find
                                  </button>
                              </div>
                          </div>
                      </form>
                      @isset($userSearchResults)
                        @if(count($userSearchResults)>0)
                          <div class="table-responsive">
                            <table class="table table-hover table-collab-people-search">
                              <thead>
                                  <tr>
                                      <th>Name</th>
                                      <th>Email</th>
                                      <th></th>
                                  </tr>
                              </thead>
                              <tbody>

                                @foreach($userSearchResults as $user)
                                  <tr>
                                      <td>{{$user->firstName}} {{$user->lastName}}</td>
                                      <td>{{$user->email}}</td>
                                      <td>
                                        <form class="" action="{{route('studies.collab.add',$study)}}" method="post">
                                          @csrf
                                          <input type="text" name="user_id" value="{{$user->id}}" hidden>
                                          <button 
                                            class="btn btn-primary btn-sm"
                                            type="submit"
                                            dusk="collab-{{$user->id}}-share-button"
                                          >
                                            Share
                                          </button>
                                        </form>

                                  </tr>
                                @endforeach

                              </tbody>
                            </table>
                          </div>
                        @endif
                      @endIsset
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container mb-2">
    <div class="row justify-content-center">
        <div class="col-md-12">

            <!-- UNREGISTERED USERS -->
            <div class="card">
                <div class="card-header">
                    <b>Add an Unregistered User by Email</b>
                </div>

                <div class="card-body">
                    <div class = "container">
                        <form class="form-horizontal" method="POST" action="{{ route('assignInvitation', $study) }}">
                            {{ csrf_field() }}

                            <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                                <label for="email" class="col-md-4 control-label">E-Mail Address</label>

                                <div class="col-md-12">
                                    <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required autofocus>

                                    @if ($errors->has('email'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('email') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-8">
                                    <button type="submit" class="btn btn-primary btn-sm">
                                        Send Invitation
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- COLLABORATORS TABLE -->
<div class="container mb-2">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <b>Collaborators of: {{$study->name}}</b>
        </div>
        <div class="card-body">
          <div class ="container">
            <div class="table-responsive">
              <table class="table table-hover table-collab-people">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  @foreach ($users as $user)
                    @if($user->can('access'.$study->id)&&!$user->hasrole('admin'))
                      <tr>
                        <td>{{$user->firstName}}</td>
                        <td>{{$user->email}}</td>
                        <td>
                          @if($user->id!==$study->user_id)
                            <form class="" action="{{route('studies.collab.remove',$study)}}" method="post">
                              @csrf
                              <input type="text" name="user_id" value="{{$user->id}}" hidden>
                              <button 
                                class="btn btn-primary btn-sm"
                                type="submit"
                                dusk="collab-{{$user->id}}-unshare-button"
                              >
                                Unshare
                              </button>
                            </form>
                          @endif
                          @if($user->id===$study->user_id)
                            Owner
                          @endif
                        </td>
                      </tr>
                    @endif
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/studies/create.blade.php
@extends('layouts.app')

@section('content')
<div class="card">
    <div class="card-header">
        <b>Create a Study</b>
    </div>

    <div class="card-body">
        <form method="POST" action="{{route('studies.basis')}}">
            @csrf
            <div class="form-group row">
                <div class="col">
                    <label for="studyName">Name of Study</label>
                    <input type="text" class="form-control" id="studyName" name="studyName" placeholder="E.g. Alzheimer Study">
                </div>
            </div>
            <div class="form-group row">
                <div class="col">
                    <label for="studyType">Study Type</label>
                    <input type="text" class="form-control" id="studyType" name="studyType" placeholder="E.g. Alzheimer">
                </div>
            </div>
            
            <button type="submit" name="button" value="basis" class="btn btn-success">Basis Set Options</button>
            <button type="submit" name="button" value ="create" class="btn btn-primary" dusk="study-create-button">Create Study</button>

        </form>

    </div>
</div>
@endsection

resources/views/studies/index.blade.php
@extends('layouts.app')

@section('content')
  <div class="card">
    <div class="card-header">
      Studies
    </div>
    <div class="card-body">
      <div class="col-12 mb-2">
        <a
          href="{{route('studies.create')}}"
          class="btn btn-primary btn-sm"
          dusk="study-add-button"
        >
          Add Study
        </a>
      </div>
      <div class="col-12">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Type</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            @foreach ($studies as $study)
              <tr>
                <td>{{$study->id}}</td>
                <td>{{$study->name}}</td>
                <td>{{$study->type}}</td>
                <td>
                  <a href="{{route('sessions.index',['study'=>$study->id])}}" class="btn btn-light btn-sm">
                    <i class="fas fa-eye"></i> View
                  </a>
                </td>
              </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
  </div>
@endsection

resources/views/studies/search.blade.php
@extends('layouts.app')

@section('content')
<div class="card">
  <div class="card-header">
    @if (!empty(request('searchStudyByName')) && !empty($studySearchResults))
    <b>Studies: <span class="badge badge-secondary">{{ $studySearchResults->count() }}</span> Results Found for "{{ request('searchStudyByName') }}"</b>
    @else
        <b>Studies: <span class="badge badge-secondary">0</span> Results Found for ""</b>
    @endif
  </div>
  <div class="card-body">
      <table class="table table-hover table-study-search-result">
          <thead>
              <tr>
                  <th>Name</th>
                  <th></th>
              </tr>
          </thead>
          <tbody>
          @if (!empty(request('searchStudyByName')) && !empty($studySearchResults))
            @foreach($studySearchResults as $study)
                    @if(auth()->user()->can('access'.$study->id))
                        <tr>
                            <td>{{ $study->name}}</td>
                            <td>
                              <a href="{{ route('studies.show', $study->id)}}" class="btn btn-light btn-sm">
                                <i class="fas fa-eye"></i> View
                              </a>
                          </td>
                        </tr>
                    @endif
                @endforeach
          @endif
          </tbody>
      </table>
  </div>


</div>
@endsection